name: Commit Message Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - edited

permissions:
  pull-requests: read
  contents: read

jobs:
  commit_naming_check:
    name: Validate PR Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0

      - name: Validate Commit Messages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: python3 scripts/commit_naming_check.py
          